# Generated by Django 3.1.5 on 2021-01-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210114_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_practicioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PracticionerProfile',
        ),
    ]
