# Generated by Django 3.1.5 on 2021-01-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210114_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, choices=[('-', '-'), ('NEUROLOGY', 'NEUROLOGY'), ('CRANIOTOMY', 'CRANIOTOMY'), ('OPTAMOLOGY', 'OPTAMOLOGY'), ('GYNAECOLOGY', 'GYNAECOLOGY'), ('UROLOGY', 'UROLOGY'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('-', '-'), ('RESIDENT', 'RESIDENT'), ('SENIOR-RESIDENT', 'SENIOR-RESIDENT'), ('ASSISTANT', 'ASSISTANT'), ('CONSULTANT', 'CONSULTANT'), ('OTHER', 'OTHER')], max_length=100, null=True),
        ),
    ]
