# Generated by Django 3.1.5 on 2021-01-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210114_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2)),
                ('under_medical_treatment', models.BooleanField(default=False)),
                ('hospitalized_within_5_years', models.BooleanField(default=False)),
                ('on_special_diet', models.BooleanField(default=False)),
                ('diseased', models.CharField(choices=[('NONE', 'NONE'), ('ARTHRITIS', 'ARTHRITIS'), ('ANAEMIA', 'ANAEMIA'), ('ASTHMA', 'ASTHMA'), ('STD', 'STD'), ('HEART FAILURE', 'HEART FAILURE'), ('EPILEPSY', 'EPILEPSY'), ('DIABETES', 'DIABETES'), ('OTHER', 'OTHER')], max_length=100)),
                ('other_disease', models.CharField(blank=True, max_length=100, null=True)),
                ('allergies', models.CharField(blank=True, max_length=1000, null=True)),
                ('pregnant', models.BooleanField(default=False)),
                ('had_any_recent_disease', models.CharField(choices=[('NONE', 'NONE'), ('HIV', 'HIV'), ('EBOLA', 'EBOLA'), ('COVID-19', 'COVID-19')], max_length=100)),
            ],
        ),
    ]
