# Generated by Django 3.1.5 on 2021-01-15 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_medicaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldetails',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_form', to='accounts.profile'),
        ),
    ]
