# Generated by Django 3.1.5 on 2021-01-15 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_medicaldetails_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaldetails',
            name='pregnant',
        ),
    ]
